name: Release - Publish polkadot deb package

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Current final release tag in the format polkadot-stableYYMM or polkadot-stable-YYMM-X
        default: polkadot-stable2412
        required: true
        type: string

      distribution:
        description: Distribution where to publish deb package (release, staging, stable2407, etc)
        default: staging
        required: true
        type: string

jobs:
  call-publish-workflow:
    uses: ./.github/workflows/release-reusable-publish-packages.yml
    with:
      tag: ${{ inputs.tag }}
      distribution: ${{ inputs.distribution }}
      package_type: 'deb'
      aws_repo_base_path: "s3://releases-package-repos"
      cloudfront_distribution_id: "E36FKEYWDXAZYJ"
    secrets: inherit
    permissions:
      id-token: write
      attestations: write
      contents: read
